### PR TITLE
Issue #2379 - Incorrect constraint violation messages for mssql-jdbc of at least 12.8.1 version

### LINKED ISSUE #2379: Incorrect constraint violation messages for `mssql-jdbc` of at least 12.8.1 version
### Description

Since `mssql-jdbc` version 12.8.1 there is a method `SQLServerError.getSQLServerMessage`, which returns `this` (self-reference). `SQLServerError` may be in a list of causes of our constraint violation error messages. However, serialisation of the above message cause fails with message `Serialisation failed. Direct self-reference leading to cycle...`.

Result instances with exceptions should be gracefully serialised with such self-references. The logic of serialising of all exception fields should be preserved as currently.

### Expected outcome

Constraint violation message for >=12.8.1 `mssql-jdbc` showing the actual error cause.

### Actual outcome

```
Serialisation failed.

Cause(s):
1. Direct self-reference leading to cycle (through reference chain: ua.com.fielden.platform.dao.exceptions.EntityDeletionException["cause"]->org.hibernate.exception.ConstraintViolationException["cause"]->com.microsoft.sqlserver.jdbc.SQLServerException["sqlserverError"]->com.microsoft.sqlserver.jdbc.SQLServerError["sqlserverMessage"])
```
message with no actual information about constraint violation error.

### Steps to reproduce

1. Go to Entity Centre with `Delete ...` action.
2. Delete entity that is a dependency in other entities.
3. Observe `Serialisation failed. Direct self-reference leading to cycle...` error.

### PR DESCRIPTION
**Pull request by jhou-pro**
Resolve #2379

# To be completed by the pull request creator

This section should be completed with reference to section [Preparing PR](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews#preparing-pr) of the [Code and PR reviews](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews) wiki page.

- [x] Converted PR to draft while it is being prepared by tapping the "Convert to draft" link beneath the "Reviewers" section.

- [x] A self-review of all changes has been completed, and the changes are in sync with the issue requirements.

- [x] Changes to the requirements have been reflected in the issue description.

- [x] All tests (all existing tests and all new tests) pass successfully.

- [x] The correct base branch has been selected for these changes to be merged into.

- [x] This pull request does not contain significant changes, and at least one appropriate reviewer has been selected.

- [x] The `In progress` label has been removed from the issue.

- [x] The `Pull request` label has been added to the issue.

- [x] Made PR ready for review by tapping the "Ready for review" button below the list of commits on the PR page.

# To be completed by the pull request reviewer

This section should be completed with reference to section [Performing PR review](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews#performing-pr-review) of the [Code and PR reviews](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews) wiki page.

- [x] The `In progress` label has been added to the pull request in GitHub.

- [x] The issue requirements have been read and understood (along with any relevant emails and/or Slack messages).

- [x] The correct base branch is specified, and that base branch is up-to-date in the local source.

- [x] The issue branch has been checked out locally, and had the base branch merged into it.

- [x] All automated tests pass successfully.

- [x] Ensure the implementation satisfies the functional requirements.

- [x] Ensure that code changes are secure and align with the established coding practices, including code formatting and naming conventions.

- [x] Ensure that code changes are documented and covered with automated tests as applicable.

- [x] Ensure that code changes are well-suited for informal reasoning.

- [x] Ensure that changes are documented for the end-user (a software engineer in the case of TG, or an application user in the case of TG-based applications).

- [x] If there are significant changes (described above), special attention has been paid to them.
      Marked the task items in section "Significant changes" as completed to indicated that corresponding changes have been reviewed, improved if necessary, and approved.

- [x] The issue or issues addressed by the pull request are associated with the relevant release milestone.

# To be completed by the pull request reviewer once the changes have been reviewed and accepted

- [x] The changes have been merged into the base branch (unless there is a specific request not to do so, e.g., they are to be released to SIT).

- [x] The issue branch has been deleted (unless the changes have not been merged - see above, or there is a specific request not to do so).

- [x] The `In progress` label has been removed from the pull request.

- [x] The `Pull request` label has been removed from the pull request.

### CODE REVIEW

File: platform-pojo-bl/src/test/java/ua/com/fielden/platform/serialisation/ResultSerialisationWithJacksonTest.java [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+    private final Object instance = "Instance";
+
+    private Result serialiseAndDeserialise(final Result result) {
+        return deserialiser.deserialise(serialiser.serialise(result, JACKSON), Result.class, JACKSON);
+    }
+
+    @Test
+    public void null_Result_serialises_and_deserialises_to_equal_value() {
+        final Result result = null;
+        assertEquals(result, serialiseAndDeserialise(result));
```
Comment (01es) [inline platform-pojo-bl/src/test/java/ua/com/fielden/platform/serialisation/ResultSerialisationWithJacksonTest.java:42]: Better to assertNull.

File: platform-pojo-bl/src/test/java/ua/com/fielden/platform/serialisation/SelfReferencingException.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
+package ua.com.fielden.platform.serialisation;
+
+/**
+ * Exception type that self-references in getter ({@link #getCause()}).
+ * See https://github.com/fieldenms/tg/issues/2379 for more details.
+ */
+public class SelfReferencingException extends RuntimeException {
```
Comment (01es) [inline platform-pojo-bl/src/test/java/ua/com/fielden/platform/serialisation/SelfReferencingException.java:7]: Should extend `AbstractPlatformRuntimeException`.

**Review by 01es — CHANGES_REQUESTED** [review]

**Review by 01es — APPROVED** [review]
